### PR TITLE
Handle concurrent recovery completion in consecutive successes strategy

### LINKED ISSUE #426: ArgumentError (comparison of Time with nil failed) - from mastodon logs
**Describe the bug**
Mastodon recently upgraded to the latest stoplight on this PR https://github.com/mastodon/mastodon/pull/35129
I've raised with the mastodon team and they believe it is upstream.

I've noticed a few 4-5 of these errors on my web logs.

```
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] ArgumentError (comparison of Time with nil failed)
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] Caused by: ArgumentError (comparison of Time with nil failed)
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25]
web-1  | Information for: ArgumentError (comparison of Time with nil failed):
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25]
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/traffic_recovery/consecutive_successes.rb:56:in 'Comparable#>='
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/traffic_recovery/consecutive_successes.rb:56:in 'Stoplight::TrafficRecovery::ConsecutiveSuccesses#determine_color'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/light/yellow_run_strategy.rb:51:in 'Stoplight::Light::YellowRunStrategy#recover'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/light/yellow_run_strategy.rb:40:in 'Stoplight::Light::YellowRunStrategy#record_recovery_probe_success'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/light/yellow_run_strategy.rb:32:in 'Stoplight::Light::YellowRunStrategy#execute'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/bundler/gems/stoplight-f13e0c0d5e6d/lib/stoplight/light.rb:76:in 'Stoplight::Light#run'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/concerns/signature_verification.rb:62:in 'SignatureVerification#signed_request_actor'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/concerns/signature_verification.rb:48:in 'SignatureVerification#signed_request_account'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/concerns/signature_authentication.rb:9:in 'SignatureAuthentication#current_account'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/concerns/authorization.rb:9:in 'Authorization#pundit_user'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/gems/pundit-2.5.0/lib/pundit/authorization.rb:35:in 'Pundit::Authorization#pundit'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /usr/local/bundle/gems/pundit-2.5.0/lib/pundit/authorization.rb:89:in 'Pundit::Authorization#authorize'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/concerns/authorization.rb:13:in 'Authorization#authorize'
web-1  | [d1c9bafc-e5cf-406e-9148-ce3d6b9cee25] /opt/mastodon/app/controllers/statuses_controller.rb:64:in 'StatusesController#set_status'
```

**To Reproduce**
I'm unable to reproduce.

**Expected behavior**
No errors in web logs.

**Screenshots**

**Environment (please complete the following information):**
* Rails 8.0.2.1 application starting in production
* Puma version: 6.6.1 ("Return to Forever")
* Ruby version: ruby 3.4.5 (2025-07-16 revision 20cda200d3) +YJIT +PRISM [x86_64-linux]
* Redis 

**Additional context**
Mastodon main branch. (bleeding edge)

### PR DESCRIPTION
**Pull request by bolshakov**
Fixes #426 

Fixes a race condition where multiple Stoplight instances could interfere with each other's recovery process. When one instance successfully completes recovery and clears the`recovery_started_at` timestamp, other instances would get `nil` and incorrectly determine circuit state.

Refactor traffic recovery to use dedicated decision types instead of reusing Color constants, improving type safety and semantic clarity.

- Add `TrafficRecovery::Decision` enum with GREEN, YELLOW, RED, PASS states
- Replace Color constants with TrafficRecovery decisions in recovery strategies
- Introduce PASS decision for the concurrent recovery completion scenariou

### CODE REVIEW

File: lib/stoplight/traffic_recovery/consecutive_successes.rb [hunk 1]
```diff
@@ -49,16 +49,18 @@ def check_compatibility(config)
       #
       # @param config [Stoplight::Light::Config]
       # @param metadata [Stoplight::Metadata]
-      # @return [String]
+      # @return [TrafficRecovery::Decision]
       def determine_color(config, metadata)
         recovery_started_at = metadata.recovery_started_at || metadata.recovery_scheduled_after
```
Comment (bolshakov) [inline lib/stoplight/traffic_recovery/consecutive_successes.rb:54]: I'm wondering this `|| metadata.recovery_scheduled_after` was added to handle a race condition, when another instance of Stoplight recovered to RED. Example:

- Instances A and B perform recovery simultaneously 
- Instance A recovers to RED (sets recovery_scheduled_after) 
- Instance B tries to receive but does not find `recovery_started_at` value.

Currently, we take `recovery_scheduled_after` instead and perform recovery. Probably it makes sense to PASS in such cases as well. @Lokideos wdyt?
